var Lz,Mz,Nz,Oz,Pz=Yf.h(He,new q(null,"name","name",1843675177));function Qz(a,b){var c=new T(null,4,5,U,[new q(null,"name","name",1843675177),new q(null,"uri","uri",-774711847),new q(null,"category","category",-593092832),new q(null,"tags-string","tags-string",-736299316)],null);if(u(a)){var d=Yf.h(Ri,new RegExp(a,"i"));return sg.h(function(a){return function(b){return ue(t(sg.h(a,vh(si(b,c)))))}}(d),b)}return b}
var Rz=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=P.k(e,0,null);return function(){var g=new T(null,1,5,U,[yr(new yh([cr,Z,new q(null,"owner","owner",-392611939),Z,new q(null,"data","data",-232669377),new yh([cr,Z,new q(null,"name","name",1843675177),Z],!0,!1)],!0,!1),new E(null,"map59695","map59695",1971969097,null))],null),k=Y(g),l=Y(Z);return Fr(function(f,g,k,l,v,x,A){return function M(C){var B=
f.P();if(u(B)){var w=new T(null,1,5,U,[C],null),y=l.j?l.j(w):l.call(null,w);if(u(y))throw W.h(X.l("Input to %s does not match schema: %s",s([new E(null,"fnk59697","fnk59697",2057770974,null),V.l(s([y],0))],0)),new n(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),w,new q(null,"error","error",-978969032),y],null));}w=function(){for(;;){if(!me(C))throw Error(X.l("fnk called on non-map: %s",s([C],0)));var I=Mr(C,new q(null,"data","data",-232669377),Yd),w=Mr(I,
new q(null,"name","name",1843675177),new T(null,1,5,U,[new q(null,"data","data",-232669377)],null)),y=Mr(C,new q(null,"owner","owner",-392611939),Yd);"undefined"===typeof Lz&&(Lz=function(a,b,c,d,e,f,g,k,l,m,p,r,z,v,x,A,B,I,w){this.Gi=a;this.wg=b;this.M=c;this.Z=d;this.$l=e;this.kj=f;this.ei=g;this.sn=k;this.zl=l;this.lj=m;this.name=p;this.aa=r;this.Wk=z;this.Bm=v;this.ca=x;this.ba=A;this.kn=B;this.Ch=I;this.jk=w;this.L=0;this.F=393216},Lz.ja=!0,Lz.ia="stuttaford.codex/t59713",Lz.la=function(){return function(a,
b){return Qc(b,"stuttaford.codex/t59713")}}(y,w,I,B,f,g,k,l,v,x,A),Lz.prototype.Aa=!0,Lz.prototype.xa=function(){return function(){return"tag-item"}}(y,w,I,B,f,g,k,l,v,x,A),Lz.prototype.Qa=!0,Lz.prototype.Ra=function(a,b,c,d,e,f,g,k,l,m,p){return function(r,z){var v=this,x=te(z)?R.h(cg,z):z,A=Q.h(x,new q(null,"search-term","search-term",356193544)),B=u(function(){var a=t(A);return a?Ri(new RegExp(A,"i"),v.name):a}())?"tag active":"tag",x={className:B,onClick:function(){return function(){return Bo.h(Rp.h(v.M,
new q(null,"search-chan","search-chan",962868037)),v.name)}}(B,this,z,x,A,a,b,c,d,e,f,g,k,l,m,p)},B=Js(v.name);return React.DOM.a(x,B)}}(y,w,I,B,f,g,k,l,v,x,A),Lz.prototype.Q=function(){return function(){return this.jk}}(y,w,I,B,f,g,k,l,v,x,A),Lz.prototype.R=function(){return function(a,b){return new Lz(this.Gi,this.wg,this.M,this.Z,this.$l,this.kj,this.ei,this.sn,this.zl,this.lj,this.name,this.aa,this.Wk,this.Bm,this.ca,this.ba,this.kn,this.Ch,b)}}(y,w,I,B,f,g,k,l,v,x,A));return new Lz(k,C,y,b,d,
C,l,x,g,I,w,A,v,e,B,f,a,M,null)}}();if(u(B)&&(y=v.j?v.j(w):v.call(null,w),u(y)))throw W.h(X.l("Output of %s does not match schema: %s",s([new E(null,"fnk59697","fnk59697",2057770974,null),V.l(s([y],0))],0)),new n(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),w,new q(null,"error","error",-978969032),y],null));return w}}(Mq,Z,g,k,l,e,f),Er(Z,new T(null,1,5,U,[g],null)))}().call(null,new n(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",
-392611939),d,new q(null,"data","data",-232669377),b],null))}a.C=2;a.w=function(a){var d=G(a);a=J(a);var e=G(a);a=H(a);return b(d,e,a)};a.l=b;return a}(),Sz=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=P.k(e,0,null);return function(){var g=new T(null,1,5,U,[yr(new yh([cr,Z,new q(null,"owner","owner",-392611939),Z,new q(null,"data","data",-232669377),new yh([cr,Z,mr(new q(null,"tags","tags",
1771418977)),Z,mr(new q(null,"image","image",-58725096)),Z,mr(new q(null,"description","description",-1428560544)),Z,new q(null,"uri","uri",-774711847),Z,new q(null,"name","name",1843675177),Z],!0,!1)],!0,!1),new E(null,"map59766","map59766",573202903,null))],null),k=Y(g),l=Y(Z);return Fr(function(f,g,k,l,v,x,A){return function M(C){var B=f.P();if(u(B)){var w=new T(null,1,5,U,[C],null),y=l.j?l.j(w):l.call(null,w);if(u(y))throw W.h(X.l("Input to %s does not match schema: %s",s([new E(null,"fnk59768",
"fnk59768",1675487719,null),V.l(s([y],0))],0)),new n(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),w,new q(null,"error","error",-978969032),y],null));}w=function(){for(;;){if(!me(C))throw Error(X.l("fnk called on non-map: %s",s([C],0)));var I=Mr(C,new q(null,"data","data",-232669377),Yd),w=Mr(I,new q(null,"name","name",1843675177),new T(null,1,5,U,[new q(null,"data","data",-232669377)],null)),y=Mr(I,new q(null,"uri","uri",-774711847),new T(null,1,5,U,[new q(null,
"data","data",-232669377)],null)),L=Q.k(I,new q(null,"description","description",-1428560544),null),S=Q.k(I,new q(null,"image","image",-58725096),null),$=Q.k(I,new q(null,"tags","tags",1771418977),Yd),na=Mr(C,new q(null,"owner","owner",-392611939),Yd);"undefined"===typeof Mz&&(Mz=function(a,b,c,d,e,f,g,k,l,m,p,r,z,v,x,A,B,I,w,y,C,S,L){this.uri=a;this.Xk=b;this.M=c;this.Z=d;this.Hi=e;this.Dh=f;this.description=g;this.og=k;this.tn=l;this.name=m;this.xg=p;this.nj=r;this.am=z;this.mj=v;this.aa=x;this.Cm=
A;this.ca=B;this.Al=I;this.ba=w;this.ej=y;this.fi=C;this.$h=S;this.kk=L;this.L=0;this.F=393216},Mz.ja=!0,Mz.ia="stuttaford.codex/t59788",Mz.la=function(){return function(a,b){return Qc(b,"stuttaford.codex/t59788")}}(na,$,S,L,y,w,I,B,f,g,k,l,v,x,A),Mz.prototype.Aa=!0,Mz.prototype.xa=function(){return function(){return"link-item"}}(na,$,S,L,y,w,I,B,f,g,k,l,v,x,A),Mz.prototype.Qa=!0,Mz.prototype.Ra=function(){return function(a,b){var c=this,d=te(b)?R.h(cg,b):b,e=Q.h(d,new q(null,"search-term","search-term",
356193544)),d=function(){var a={href:c.uri},b=Js(c.name);return React.DOM.a(a,b)}(),e=Js(jq.k(Rz,function(){var a=c.og;return Pz.j?Pz.j(a):Pz.call(null,a)}(),new n(null,2,[new q(null,"state","state",-1988618099),new n(null,1,[new q(null,"search-term","search-term",356193544),e],null),new q(null,"key","key",-1516042587),new q(null,"name","name",1843675177)],null)));return React.DOM.li({className:"link"},d,e)}}(na,$,S,L,y,w,I,B,f,g,k,l,v,x,A),Mz.prototype.Q=function(){return function(){return this.kk}}(na,
$,S,L,y,w,I,B,f,g,k,l,v,x,A),Mz.prototype.R=function(){return function(a,b){return new Mz(this.uri,this.Xk,this.M,this.Z,this.Hi,this.Dh,this.description,this.og,this.tn,this.name,this.xg,this.nj,this.am,this.mj,this.aa,this.Cm,this.ca,this.Al,this.ba,this.ej,this.fi,this.$h,b)}}(na,$,S,L,y,w,I,B,f,g,k,l,v,x,A));return new Mz(y,v,na,b,k,M,L,$,x,w,C,I,d,C,A,e,B,g,f,a,l,S,null)}}();if(u(B)&&(y=v.j?v.j(w):v.call(null,w),u(y)))throw W.h(X.l("Output of %s does not match schema: %s",s([new E(null,"fnk59768",
"fnk59768",1675487719,null),V.l(s([y],0))],0)),new n(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),w,new q(null,"error","error",-978969032),y],null));return w}}(Mq,Z,g,k,l,e,f),Er(Z,new T(null,1,5,U,[g],null)))}().call(null,new n(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",-392611939),d,new q(null,"data","data",-232669377),b],null))}a.C=2;a.w=function(a){var d=G(a);a=J(a);var e=G(a);a=H(a);return b(d,e,a)};a.l=b;return a}(),
Tz=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=P.k(e,0,null);return function(){var g=new T(null,1,5,U,[yr(new yh([cr,Z,new q(null,"owner","owner",-392611939),Z,new q(null,"data","data",-232669377),new yh([cr,Z,new q(null,"links","links",-654507394),Z,new q(null,"name","name",1843675177),Z],!0,!1)],!0,!1),new E(null,"map59844","map59844",1390971881,null))],null),k=Y(g),l=Y(Z);return Fr(function(f,
g,k,l,v,x,A){return function M(C){var B=f.P();if(u(B)){var w=new T(null,1,5,U,[C],null),y=l.j?l.j(w):l.call(null,w);if(u(y))throw W.h(X.l("Input to %s does not match schema: %s",s([new E(null,"fnk59845","fnk59845",-2065839248,null),V.l(s([y],0))],0)),new n(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),w,new q(null,"error","error",-978969032),y],null));}w=function(){for(;;){if(!me(C))throw Error(X.l("fnk called on non-map: %s",s([C],0)));var I=Mr(C,new q(null,
"data","data",-232669377),Yd),w=Mr(I,new q(null,"name","name",1843675177),new T(null,1,5,U,[new q(null,"data","data",-232669377)],null)),y=Mr(I,new q(null,"links","links",-654507394),new T(null,1,5,U,[new q(null,"data","data",-232669377)],null)),L=Mr(C,new q(null,"owner","owner",-392611939),Yd);"undefined"===typeof Nz&&(Nz=function(a,b,c,d,e,f,g,k,l,m,p,r,z,v,x,A,B,I,w,y){this.Dm=a;this.Yk=b;this.M=c;this.links=d;this.Z=e;this.data=f;this.un=g;this.oj=k;this.bm=l;this.yg=m;this.name=p;this.Eh=r;this.Ii=
z;this.gi=v;this.Bl=x;this.aa=A;this.Xg=B;this.ca=I;this.ba=w;this.lk=y;this.L=0;this.F=393216},Nz.ja=!0,Nz.ia="stuttaford.codex/t59865",Nz.la=function(){return function(a,b){return Qc(b,"stuttaford.codex/t59865")}}(L,y,w,I,B,f,g,k,l,v,x,A),Nz.prototype.Aa=!0,Nz.prototype.xa=function(){return function(){return"category-item"}}(L,y,w,I,B,f,g,k,l,v,x,A),Nz.prototype.Qa=!0,Nz.prototype.Ra=function(){return function(a,b){var c=this,d=te(b)?R.h(cg,b):b,e=Q.h(d,new q(null,"search-term","search-term",356193544)),
f=t(function(){var a=Qz(e,c.links);return Pz.j?Pz.j(a):Pz.call(null,a)}());if(f){var d=function(){var a=c.name;return R.k(React.DOM.h3,me(a)?Os(a):null,tg.h(Hb,me(a)?Yd:new T(null,1,5,U,[Js(a)],null)))}(),g=function(){var a=jq.k(Sz,f,new n(null,2,[new q(null,"state","state",-1988618099),new n(null,1,[new q(null,"search-term","search-term",356193544),e],null),new q(null,"key","key",-1516042587),new q(null,"name","name",1843675177)],null));return R.k(React.DOM.ul,me(a)?Os(a):null,tg.h(Hb,me(a)?Yd:new T(null,
1,5,U,[Js(a)],null)))}();return React.DOM.div(null,d,g)}return null}}(L,y,w,I,B,f,g,k,l,v,x,A),Nz.prototype.Q=function(){return function(){return this.lk}}(L,y,w,I,B,f,g,k,l,v,x,A),Nz.prototype.R=function(){return function(a,b){return new Nz(this.Dm,this.Yk,this.M,this.links,this.Z,this.data,this.un,this.oj,this.bm,this.yg,this.name,this.Eh,this.Ii,this.gi,this.Bl,this.aa,this.Xg,this.ca,this.ba,b)}}(L,y,w,I,B,f,g,k,l,v,x,A));return new Nz(e,v,L,y,b,I,x,C,d,C,w,M,k,l,g,A,a,B,f,null)}}();if(u(B)&&
(y=v.j?v.j(w):v.call(null,w),u(y)))throw W.h(X.l("Output of %s does not match schema: %s",s([new E(null,"fnk59845","fnk59845",-2065839248,null),V.l(s([y],0))],0)),new n(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),w,new q(null,"error","error",-978969032),y],null));return w}}(Mq,Z,g,k,l,e,f),Er(Z,new T(null,1,5,U,[g],null)))}().call(null,new n(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",-392611939),d,new q(null,"data","data",
-232669377),b],null))}a.C=2;a.w=function(a){var d=G(a);a=J(a);var e=G(a);a=H(a);return b(d,e,a)};a.l=b;return a}(),Uz=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=P.k(e,0,null);return function(){var g=new T(null,1,5,U,[yr(new yh([cr,Z,new q(null,"owner","owner",-392611939),Z,new q(null,"data","data",-232669377),new yh([cr,Z,new q(null,"categories","categories",178386610),Z],!0,!1)],!0,
!1),new E(null,"map59995","map59995",2003253,null))],null),k=Y(g),l=Y(Z);return Fr(function(f,g,k,l,v,x,A){return function M(C){var B=f.P();if(u(B)){var w=new T(null,1,5,U,[C],null),y=l.j?l.j(w):l.call(null,w);if(u(y))throw W.h(X.l("Input to %s does not match schema: %s",s([new E(null,"fnk59997","fnk59997",593167442,null),V.l(s([y],0))],0)),new n(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),w,new q(null,"error","error",-978969032),y],null));}w=function(){for(;;){if(!me(C))throw Error(X.l("fnk called on non-map: %s",
s([C],0)));var I=Mr(C,new q(null,"data","data",-232669377),Yd),w=Mr(I,new q(null,"categories","categories",178386610),new T(null,1,5,U,[new q(null,"data","data",-232669377)],null)),y=Mr(C,new q(null,"owner","owner",-392611939),Yd);"undefined"===typeof Oz&&(Oz=function(a,b,c,d,e,f,g,k,l,m,p,r,z,v,x,A,B,w,I){this.Oc=a;this.M=b;this.Z=c;this.Zk=d;this.Ji=e;this.Em=f;this.zg=g;this.Fh=k;this.hi=l;this.pj=m;this.qj=p;this.cm=r;this.aa=z;this.vn=v;this.of=x;this.ca=A;this.Cl=B;this.ba=w;this.mk=I;this.L=
0;this.F=393216},Oz.ja=!0,Oz.ia="stuttaford.codex/t60053",Oz.la=function(){return function(a,b){return Qc(b,"stuttaford.codex/t60053")}}(y,w,I,B,f,g,k,l,v,x,A),Oz.prototype.Aa=!0,Oz.prototype.xa=function(){return function(){return"app-view"}}(y,w,I,B,f,g,k,l,v,x,A),Oz.prototype.Qa=!0,Oz.prototype.Ra=function(a,b,c,d,e,f,g,k,l,m,p){return function(r,z){var v=this,x=te(z)?R.h(cg,z):z,A=Q.h(x,new q(null,"search-term","search-term",356193544)),B=Q.h(x,new q(null,"search-chan","search-chan",962868037)),
w=this,I=function(){var r={id:"search",type:"text",placeholder:"Search for link",autoFocus:"autofocus",value:A,onChange:function(a,b,c,d,e,f){return function(a){return Bo.h(f,a.target.value)}}(null,w,z,x,A,B,a,b,c,d,e,f,g,k,l,m,p)};return Ls.j?Ls.j(r):Ls.call(null,r)}(),y=Js(jq.k(Tz,function(){var a=v.of;return Pz.j?Pz.j(a):Pz.call(null,a)}(),new n(null,2,[new q(null,"state","state",-1988618099),new n(null,1,[new q(null,"search-term","search-term",356193544),A],null),new q(null,"key","key",-1516042587),
new q(null,"name","name",1843675177)],null)));return React.DOM.div(null,I,y)}}(y,w,I,B,f,g,k,l,v,x,A),Oz.prototype.te=!0,Oz.prototype.Kd=function(a,b,c,d,e,f,g,k,l,m,p){return function(){var r=this,z=Qp.h(r.M,new q(null,"search-chan","search-chan",962868037)),v=zo.j(1);io(function(a,b,c,d,e,f,g,k,l,m,p,z,v,x){return function(){var A=function(){return function(a){return function(){function b(c){for(;;){var d;a:{try{for(;;){var e=a(c);if(!qf(e,new q(null,"recur","recur",-437573268))){d=e;break a}}}catch(f){if(f instanceof
Object){c[5]=f;vo(c);d=new q(null,"recur","recur",-437573268);break a}throw f;}d=void 0}if(!qf(d,new q(null,"recur","recur",-437573268)))return d}}function c(){var a=[null,null,null,null,null,null,null,null,null];a[0]=d;a[1]=1;return a}var d=null,d=function(a){switch(arguments.length){case 0:return c.call(this);case 1:return b.call(this,a)}throw Error("Invalid arity: "+arguments.length);};d.G=c;d.j=b;return d}()}(function(a,b){return function(a){var c=a[1];return 7===c?(c=a[7],c=a[2],a[7]=c,a[1]=
u(c)?8:9,new q(null,"recur","recur",-437573268)):1===c?(a[2]=null,a[1]=2,new q(null,"recur","recur",-437573268)):4===c?to(a,7,b):6===c?(c=a[2],a[2]=c,a[1]=3,new q(null,"recur","recur",-437573268)):3===c?(c=a[2],uo(a,c)):2===c?(a[1]=4,new q(null,"recur","recur",-437573268)):9===c?(a[2]=null,a[1]=10,new q(null,"recur","recur",-437573268)):5===c?(a[2]=null,a[1]=6,new q(null,"recur","recur",-437573268)):10===c?(a[8]=a[2],a[2]=null,a[1]=2,new q(null,"recur","recur",-437573268)):8===c?(c=a[7],c=pq.k(r.M,
new q(null,"search-term","search-term",356193544),c),a[2]=c,a[1]=10,new q(null,"recur","recur",-437573268)):null}}(a,b,c,d,e,f,g,k,l,m,p,z,v,x),a,b,c,d,e,f,g,k,l,m,p,z,v,x)}(),B=function(){var b=A.G?A.G():A.call(null);b[6]=a;return b}();return so(B)}}(v,z,this,a,b,c,d,e,f,g,k,l,m,p));return v}}(y,w,I,B,f,g,k,l,v,x,A),Oz.prototype.bf=!0,Oz.prototype.re=function(){return function(){return new n(null,1,[new q(null,"search-chan","search-chan",962868037),zo.G()],null)}}(y,w,I,B,f,g,k,l,v,x,A),Oz.prototype.Q=
function(){return function(){return this.mk}}(y,w,I,B,f,g,k,l,v,x,A),Oz.prototype.R=function(){return function(a,b){return new Oz(this.Oc,this.M,this.Z,this.Zk,this.Ji,this.Em,this.zg,this.Fh,this.hi,this.pj,this.qj,this.cm,this.aa,this.vn,this.of,this.ca,this.Cl,this.ba,b)}}(y,w,I,B,f,g,k,l,v,x,A));return new Oz(a,y,b,v,k,e,C,M,l,C,I,d,A,x,w,B,g,f,null)}}();if(u(B)&&(y=v.j?v.j(w):v.call(null,w),u(y)))throw W.h(X.l("Output of %s does not match schema: %s",s([new E(null,"fnk59997","fnk59997",593167442,
null),V.l(s([y],0))],0)),new n(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),w,new q(null,"error","error",-978969032),y],null));return w}}(Mq,Z,g,k,l,e,f),Er(Z,new T(null,1,5,U,[g],null)))}().call(null,new n(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",-392611939),d,new q(null,"data","data",-232669377),b],null))}a.C=2;a.w=function(a){var d=G(a);a=J(a);var e=G(a);a=H(a);return b(d,e,a)};a.l=b;return a}();
pa("stuttaford.codex.init",function(a,b,c){return tq.U(a,b,Uz,ze,c)});
//# sourceMappingURL=src/codex.js.map
