var Gu,Hu,Iu,Ju,Ku=Yf.e(He,new q(null,"name","name",1843675177));function Lu(a,b){var c=new P(null,4,5,Q,[new q(null,"name","name",1843675177),new q(null,"uri","uri",-774711847),new q(null,"category","category",-593092832),new q(null,"tags-string","tags-string",-736299316)],null);if(u(a)){var d=Yf.e(Ki,new RegExp(a,"i"));return sg.e(function(a){return function(b){return ue(t(sg.e(a,rh(pi(b,c)))))}}(d),b)}return b}
var Mu=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=M.j(e,0,null);return function(){var g=new P(null,1,5,Q,[cr(new uh([Jq,$,new q(null,"owner","owner",-392611939),$,new q(null,"data","data",-232669377),new uh([Jq,$,new q(null,"name","name",1843675177),$],!0,!1)],!0,!1),new B(null,"map71213","map71213",1554003016,null))],null),k=Y(g),l=Y($);return jr(function(f,g,k,l,v,x,z){return function L(E){var G=
f.Q();if(u(G)){var C=new P(null,1,5,Q,[E],null),y=l.h?l.h(C):l.call(null,C);if(u(y))throw T.e(V.k("Input to %s does not match schema: %s",s([new B(null,"fnk71215","fnk71215",1366112933,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));}C=function(){for(;;){if(!me(E))throw Error(V.k("fnk called on non-map: %s",s([E],0)));var H=qr(E,new q(null,"data","data",-232669377),Xd),y=qr(H,
new q(null,"name","name",1843675177),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),C=qr(E,new q(null,"owner","owner",-392611939),Xd);"undefined"===typeof Gu&&(Gu=function(a,b,c,d,e,f,g,k,l,n,p,r,w,v,x,z,H,E,G){this.X=a;this.bh=b;this.Mj=c;this.ai=d;this.ma=e;this.oa=f;this.ij=g;this.Jh=k;this.bi=l;this.name=n;this.jg=p;this.xj=r;this.ak=w;this.uh=v;this.qa=x;this.Fk=z;this.pa=H;this.zk=E;this.Hi=G;this.J=0;this.C=393216},Gu.Na=!0,Gu.La="stuttaford.codex/t71231",Gu.Pa=function(){return function(a,
b){return Qc(b,"stuttaford.codex/t71231")}}(C,y,H,G,f,g,k,l,v,x,z),Gu.prototype.wb=!0,Gu.prototype.pb=function(){return function(){return"tag-item"}}(C,y,H,G,f,g,k,l,v,x,z),Gu.prototype.Qb=!0,Gu.prototype.Rb=function(a,b,c,d,e,f,g,k,l,n,p){return function(r,w){var v=this,x=te(w)?O.e(cg,w):w,z=N.e(x,new q(null,"search-term","search-term",356193544)),H=u(function(){var a=t(z);return a?Ki(new RegExp(z,"i"),v.name):a}())?"tag active":"tag",x={className:H,onClick:function(){return function(){return ho.e(xp.e(v.X,
new q(null,"search-chan","search-chan",962868037)),v.name)}}(H,this,w,x,z,a,b,c,d,e,f,g,k,l,n,p)},H=ns(v.name);return React.DOM.a(x,H)}}(C,y,H,G,f,g,k,l,v,x,z),Gu.prototype.O=function(){return function(){return this.Hi}}(C,y,H,G,f,g,k,l,v,x,z),Gu.prototype.P=function(){return function(a,b){return new Gu(this.X,this.bh,this.Mj,this.ai,this.ma,this.oa,this.ij,this.Jh,this.bi,this.name,this.jg,this.xj,this.ak,this.uh,this.qa,this.Fk,this.pa,this.zk,b)}}(C,y,H,G,f,g,k,l,v,x,z));return new Gu(C,L,d,E,
b,z,v,k,H,y,E,g,e,l,G,x,f,a,null)}}();if(u(G)&&(y=v.h?v.h(C):v.call(null,C),u(y)))throw T.e(V.k("Output of %s does not match schema: %s",s([new B(null,"fnk71215","fnk71215",1366112933,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));return C}}(rq,$,g,k,l,e,f),ir($,new P(null,1,5,Q,[g],null)))}().call(null,new m(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner",
"owner",-392611939),d,new q(null,"data","data",-232669377),b],null))}a.A=2;a.o=function(a){var d=F(a);a=J(a);var e=F(a);a=I(a);return b(d,e,a)};a.k=b;return a}(),Nu=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=M.j(e,0,null);return function(){var g=new P(null,1,5,Q,[cr(new uh([Jq,$,new q(null,"owner","owner",-392611939),$,new q(null,"data","data",-232669377),new uh([Jq,$,Sq(new q(null,
"tags","tags",1771418977)),$,Sq(new q(null,"image","image",-58725096)),$,Sq(new q(null,"description","description",-1428560544)),$,new q(null,"uri","uri",-774711847),$,new q(null,"name","name",1843675177),$],!0,!1)],!0,!1),new B(null,"map71284","map71284",-282384220,null))],null),k=Y(g),l=Y($);return jr(function(f,g,k,l,v,x,z){return function L(E){var G=f.Q();if(u(G)){var C=new P(null,1,5,Q,[E],null),y=l.h?l.h(C):l.call(null,C);if(u(y))throw T.e(V.k("Input to %s does not match schema: %s",s([new B(null,
"fnk71286","fnk71286",-1844594615,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));}C=function(){for(;;){if(!me(E))throw Error(V.k("fnk called on non-map: %s",s([E],0)));var H=qr(E,new q(null,"data","data",-232669377),Xd),y=qr(H,new q(null,"name","name",1843675177),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),C=qr(H,new q(null,"uri","uri",-774711847),new P(null,
1,5,Q,[new q(null,"data","data",-232669377)],null)),R=N.j(H,new q(null,"description","description",-1428560544),null),X=N.j(H,new q(null,"image","image",-58725096),null),Z=N.j(H,new q(null,"tags","tags",1771418977),Xd),ma=qr(E,new q(null,"owner","owner",-392611939),Xd);"undefined"===typeof Hu&&(Hu=function(a,b,c,d,e,f,g,k,l,n,p,r,w,v,x,z,H,E,G,y,C,W,R){this.kg=a;this.uri=b;this.ci=c;this.X=d;this.Nj=e;this.description=f;this.yj=g;this.fg=k;this.dh=l;this.ma=n;this.oa=p;this.Gk=r;this.name=w;this.di=
v;this.bk=x;this.jj=z;this.vh=H;this.qa=E;this.Kh=G;this.pa=y;this.$h=C;this.sh=W;this.Ii=R;this.J=0;this.C=393216},Hu.Na=!0,Hu.La="stuttaford.codex/t71306",Hu.Pa=function(){return function(a,b){return Qc(b,"stuttaford.codex/t71306")}}(ma,Z,X,R,C,y,H,G,f,g,k,l,v,x,z),Hu.prototype.wb=!0,Hu.prototype.pb=function(){return function(){return"link-item"}}(ma,Z,X,R,C,y,H,G,f,g,k,l,v,x,z),Hu.prototype.Qb=!0,Hu.prototype.Rb=function(){return function(a,b){var c=this,d=te(b)?O.e(cg,b):b,e=N.e(d,new q(null,
"search-term","search-term",356193544)),d=function(){var a={href:c.uri},b=ns(c.name);return React.DOM.a(a,b)}(),e=ns(Qp.j(Mu,function(){var a=c.fg;return Ku.h?Ku.h(a):Ku.call(null,a)}(),new m(null,2,[new q(null,"state","state",-1988618099),new m(null,1,[new q(null,"search-term","search-term",356193544),e],null),new q(null,"key","key",-1516042587),new q(null,"name","name",1843675177)],null)));return React.DOM.li({className:"link"},d,e)}}(ma,Z,X,R,C,y,H,G,f,g,k,l,v,x,z),Hu.prototype.O=function(){return function(){return this.Ii}}(ma,
Z,X,R,C,y,H,G,f,g,k,l,v,x,z),Hu.prototype.P=function(){return function(a,b){return new Hu(this.kg,this.uri,this.ci,this.X,this.Nj,this.description,this.yj,this.fg,this.dh,this.ma,this.oa,this.Gk,this.name,this.di,this.bk,this.jj,this.vh,this.qa,this.Kh,this.pa,this.$h,this.sh,b)}}(ma,Z,X,R,C,y,H,G,f,g,k,l,v,x,z));return new Hu(E,C,E,ma,d,R,g,Z,L,b,z,x,y,H,e,v,l,G,k,f,a,X,null)}}();if(u(G)&&(y=v.h?v.h(C):v.call(null,C),u(y)))throw T.e(V.k("Output of %s does not match schema: %s",s([new B(null,"fnk71286",
"fnk71286",-1844594615,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));return C}}(rq,$,g,k,l,e,f),ir($,new P(null,1,5,Q,[g],null)))}().call(null,new m(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",-392611939),d,new q(null,"data","data",-232669377),b],null))}a.A=2;a.o=function(a){var d=F(a);a=J(a);var e=F(a);a=I(a);return b(d,e,a)};a.k=b;return a}(),
Ou=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=M.j(e,0,null);return function(){var g=new P(null,1,5,Q,[cr(new uh([Jq,$,new q(null,"owner","owner",-392611939),$,new q(null,"data","data",-232669377),new uh([Jq,$,new q(null,"links","links",-654507394),$,new q(null,"name","name",1843675177),$],!0,!1)],!0,!1),new B(null,"map71362","map71362",813749868,null))],null),k=Y(g),l=Y($);return jr(function(f,
g,k,l,v,x,z){return function L(E){var G=f.Q();if(u(G)){var C=new P(null,1,5,Q,[E],null),y=l.h?l.h(C):l.call(null,C);if(u(y))throw T.e(V.k("Input to %s does not match schema: %s",s([new B(null,"fnk71363","fnk71363",-401877719,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));}C=function(){for(;;){if(!me(E))throw Error(V.k("fnk called on non-map: %s",s([E],0)));var H=qr(E,new q(null,
"data","data",-232669377),Xd),y=qr(H,new q(null,"name","name",1843675177),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),C=qr(H,new q(null,"links","links",-654507394),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),R=qr(E,new q(null,"owner","owner",-392611939),Xd);"undefined"===typeof Iu&&(Iu=function(a,b,c,d,e,f,g,k,l,n,p,r,w,v,x,z,H,E,y,G){this.ck=a;this.X=b;this.links=c;this.data=d;this.eh=e;this.ma=f;this.oa=g;this.wh=k;this.ei=l;this.Hk=n;this.name=p;this.lg=r;
this.zj=w;this.Lh=v;this.kj=x;this.Oj=z;this.Cg=H;this.qa=E;this.pa=y;this.Ji=G;this.J=0;this.C=393216},Iu.Na=!0,Iu.La="stuttaford.codex/t71383",Iu.Pa=function(){return function(a,b){return Qc(b,"stuttaford.codex/t71383")}}(R,C,y,H,G,f,g,k,l,v,x,z),Iu.prototype.wb=!0,Iu.prototype.pb=function(){return function(){return"category-item"}}(R,C,y,H,G,f,g,k,l,v,x,z),Iu.prototype.Qb=!0,Iu.prototype.Rb=function(){return function(a,b){var c=this,d=te(b)?O.e(cg,b):b,e=N.e(d,new q(null,"search-term","search-term",
356193544)),f=t(function(){var a=Lu(e,c.links);return Ku.h?Ku.h(a):Ku.call(null,a)}());if(f){var d=function(){var a=c.name;return O.j(React.DOM.h3,me(a)?ss(a):null,tg.e(Gb,me(a)?Xd:new P(null,1,5,Q,[ns(a)],null)))}(),g=function(){var a=Qp.j(Nu,f,new m(null,2,[new q(null,"state","state",-1988618099),new m(null,1,[new q(null,"search-term","search-term",356193544),e],null),new q(null,"key","key",-1516042587),new q(null,"name","name",1843675177)],null));return O.j(React.DOM.ul,me(a)?ss(a):null,tg.e(Gb,
me(a)?Xd:new P(null,1,5,Q,[ns(a)],null)))}();return React.DOM.div(null,d,g)}return null}}(R,C,y,H,G,f,g,k,l,v,x,z),Iu.prototype.O=function(){return function(){return this.Ji}}(R,C,y,H,G,f,g,k,l,v,x,z),Iu.prototype.P=function(){return function(a,b){return new Iu(this.ck,this.X,this.links,this.data,this.eh,this.ma,this.oa,this.wh,this.ei,this.Hk,this.name,this.lg,this.zj,this.Lh,this.kj,this.Oj,this.Cg,this.qa,this.pa,b)}}(R,C,y,H,G,f,g,k,l,v,x,z));return new Iu(e,R,C,H,L,b,z,l,E,x,y,E,g,k,v,d,a,G,
f,null)}}();if(u(G)&&(y=v.h?v.h(C):v.call(null,C),u(y)))throw T.e(V.k("Output of %s does not match schema: %s",s([new B(null,"fnk71363","fnk71363",-401877719,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));return C}}(rq,$,g,k,l,e,f),ir($,new P(null,1,5,Q,[g],null)))}().call(null,new m(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",-392611939),d,new q(null,
"data","data",-232669377),b],null))}a.A=2;a.o=function(a){var d=F(a);a=J(a);var e=F(a);a=I(a);return b(d,e,a)};a.k=b;return a}(),Pu=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=M.j(e,0,null);return function(){var g=new P(null,1,5,Q,[cr(new uh([Jq,$,new q(null,"owner","owner",-392611939),$,new q(null,"data","data",-232669377),new uh([Jq,$,new q(null,"categories","categories",178386610),
$],!0,!1)],!0,!1),new B(null,"map71513","map71513",1323378080,null))],null),k=Y(g),l=Y($);return jr(function(f,g,k,l,v,x,z){return function L(E){var G=f.Q();if(u(G)){var C=new P(null,1,5,Q,[E],null),y=l.h?l.h(C):l.call(null,C);if(u(y))throw T.e(V.k("Input to %s does not match schema: %s",s([new B(null,"fnk71515","fnk71515",-2079551485,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],
null));}C=function(){for(;;){if(!me(E))throw Error(V.k("fnk called on non-map: %s",s([E],0)));var H=qr(E,new q(null,"data","data",-232669377),Xd),y=qr(H,new q(null,"categories","categories",178386610),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),C=qr(E,new q(null,"owner","owner",-392611939),Xd);"undefined"===typeof Ju&&(Ju=function(a,b,c,d,e,f,g,k,l,n,p,r,w,v,x,z,H,E,y){this.fi=a;this.Pj=b;this.Ae=c;this.fh=d;this.X=e;this.Mh=f;this.lj=g;this.ma=k;this.oa=l;this.dk=n;this.xh=p;this.Aj=
r;this.mg=w;this.Ik=v;this.ff=x;this.gi=z;this.qa=H;this.pa=E;this.Ki=y;this.J=0;this.C=393216},Ju.Na=!0,Ju.La="stuttaford.codex/t71571",Ju.Pa=function(){return function(a,b){return Qc(b,"stuttaford.codex/t71571")}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.wb=!0,Ju.prototype.pb=function(){return function(){return"app-view"}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.Qb=!0,Ju.prototype.Rb=function(a,b,c,d,e,f,g,k,l,n,p){return function(r,w){var v=this,x=te(w)?O.e(cg,w):w,z=N.e(x,new q(null,"search-term","search-term",
356193544)),H=N.e(x,new q(null,"search-chan","search-chan",962868037)),E=this,y=function(){var r={id:"search",type:"text",placeholder:"Search for link",autoFocus:"autofocus",value:z,onChange:function(a,b,c,d,e,f){return function(a){return ho.e(f,a.target.value)}}(null,E,w,x,z,H,a,b,c,d,e,f,g,k,l,n,p)};return ps.h?ps.h(r):ps.call(null,r)}(),G=ns(Qp.j(Ou,function(){var a=v.ff;return Ku.h?Ku.h(a):Ku.call(null,a)}(),new m(null,2,[new q(null,"state","state",-1988618099),new m(null,1,[new q(null,"search-term",
"search-term",356193544),z],null),new q(null,"key","key",-1516042587),new q(null,"name","name",1843675177)],null)));return React.DOM.div(null,y,G)}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.Xf=!0,Ju.prototype.We=function(a,b,c,d,e,f,g,k,l,n,p){return function(){var r=this,w=wp.e(r.X,new q(null,"search-chan","search-chan",962868037)),v=fo.h(1);On(function(a,b,c,d,e,f,g,k,l,n,p,w,v,x){return function(){var z=function(){return function(a){return function(){function b(c){for(;;){var d;a:{try{for(;;){var e=
a(c);if(!rf(e,new q(null,"recur","recur",-437573268))){d=e;break a}}}catch(f){if(f instanceof Object){c[5]=f;ao(c);d=new q(null,"recur","recur",-437573268);break a}throw f;}d=void 0}if(!rf(d,new q(null,"recur","recur",-437573268)))return d}}function c(){var a=[null,null,null,null,null,null,null,null,null];a[0]=d;a[1]=1;return a}var d=null,d=function(a){switch(arguments.length){case 0:return c.call(this);case 1:return b.call(this,a)}throw Error("Invalid arity: "+arguments.length);};d.F=c;d.h=b;return d}()}(function(a,
b){return function(a){var c=a[1];return 7===c?(c=a[7],c=a[2],a[7]=c,a[1]=u(c)?8:9,new q(null,"recur","recur",-437573268)):1===c?(a[2]=null,a[1]=2,new q(null,"recur","recur",-437573268)):4===c?Zn(a,7,b):6===c?(c=a[2],a[2]=c,a[1]=3,new q(null,"recur","recur",-437573268)):3===c?(c=a[2],$n(a,c)):2===c?(a[1]=4,new q(null,"recur","recur",-437573268)):9===c?(a[2]=null,a[1]=10,new q(null,"recur","recur",-437573268)):5===c?(a[2]=null,a[1]=6,new q(null,"recur","recur",-437573268)):10===c?(a[8]=a[2],a[2]=null,
a[1]=2,new q(null,"recur","recur",-437573268)):8===c?(c=a[7],c=Wp.j(r.X,new q(null,"search-term","search-term",356193544),c),a[2]=c,a[1]=10,new q(null,"recur","recur",-437573268)):null}}(a,b,c,d,e,f,g,k,l,n,p,w,v,x),a,b,c,d,e,f,g,k,l,n,p,w,v,x)}(),H=function(){var b=z.F?z.F():z.call(null);b[6]=a;return b}();return Yn(H)}}(v,w,this,a,b,c,d,e,f,g,k,l,n,p));return v}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.Kf=!0,Ju.prototype.Ve=function(){return function(){return new m(null,1,[new q(null,"search-chan",
"search-chan",962868037),fo.F()],null)}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.O=function(){return function(){return this.Ki}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.P=function(){return function(a,b){return new Ju(this.fi,this.Pj,this.Ae,this.fh,this.X,this.Mh,this.lj,this.ma,this.oa,this.dk,this.xh,this.Aj,this.mg,this.Ik,this.ff,this.gi,this.qa,this.pa,b)}}(C,y,H,G,f,g,k,l,v,x,z));return new Ju(E,d,a,L,C,k,v,b,z,e,l,g,E,x,y,H,G,f,null)}}();if(u(G)&&(y=v.h?v.h(C):v.call(null,C),u(y)))throw T.e(V.k("Output of %s does not match schema: %s",
s([new B(null,"fnk71515","fnk71515",-2079551485,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));return C}}(rq,$,g,k,l,e,f),ir($,new P(null,1,5,Q,[g],null)))}().call(null,new m(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",-392611939),d,new q(null,"data","data",-232669377),b],null))}a.A=2;a.o=function(a){var d=F(a);a=J(a);var e=F(a);a=I(a);return b(d,
e,a)};a.k=b;return a}();qa("stuttaford.codex.init",function(a,b,c){return Zp.R(a,b,Pu,ze,c)});
//# sourceMappingURL=src/codex.js.map
