var Gu,Hu,Iu,Ju,Ku=Yf.e(He,new q(null,"name","name",1843675177));function Lu(a,b){var c=new P(null,4,5,Q,[new q(null,"name","name",1843675177),new q(null,"uri","uri",-774711847),new q(null,"category","category",-593092832),new q(null,"tags-string","tags-string",-736299316)],null);if(u(a)){var d=Yf.e(Ki,new RegExp(a,"i"));return sg.e(function(a){return function(b){return ue(t(sg.e(a,rh(pi(b,c)))))}}(d),b)}return b}
var Mu=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=M.j(e,0,null);return function(){var g=new P(null,1,5,Q,[cr(new uh([Jq,$,new q(null,"owner","owner",-392611939),$,new q(null,"data","data",-232669377),new uh([Jq,$,new q(null,"name","name",1843675177),$],!0,!1)],!0,!1),new B(null,"map74624","map74624",1694488500,null))],null),k=Y(g),l=Y($);return jr(function(f,g,k,l,v,x,z){return function L(E){var G=
f.Q();if(u(G)){var C=new P(null,1,5,Q,[E],null),y=l.h?l.h(C):l.call(null,C);if(u(y))throw T.e(V.k("Input to %s does not match schema: %s",s([new B(null,"fnk74626","fnk74626",1227357911,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));}C=function(){for(;;){if(!me(E))throw Error(V.k("fnk called on non-map: %s",s([E],0)));var H=qr(E,new q(null,"data","data",-232669377),Xd),y=qr(H,
new q(null,"name","name",1843675177),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),C=qr(E,new q(null,"owner","owner",-392611939),Xd);"undefined"===typeof Gu&&(Gu=function(a,b,c,d,e,f,g,k,l,n,p,r,w,v,x,z,H,E,G){this.ng=a;this.X=b;this.ek=c;this.gi=d;this.yh=e;this.ma=f;this.oa=g;this.Jk=k;this.mj=l;this.name=n;this.Qj=p;this.fi=r;this.gh=w;this.Bj=v;this.qa=x;this.pa=z;this.zk=H;this.Nh=E;this.Li=G;this.J=0;this.C=393216},Gu.Na=!0,Gu.La="stuttaford.codex/t74646",Gu.Pa=function(){return function(a,
b){return Qc(b,"stuttaford.codex/t74646")}}(C,y,H,G,f,g,k,l,v,x,z),Gu.prototype.wb=!0,Gu.prototype.pb=function(){return function(){return"tag-item"}}(C,y,H,G,f,g,k,l,v,x,z),Gu.prototype.Qb=!0,Gu.prototype.Rb=function(a,b,c,d,e,f,g,k,l,n,p){return function(r,w){var v=this,x=te(w)?O.e(cg,w):w,z=N.e(x,new q(null,"search-term","search-term",356193544)),H=u(function(){var a=t(z);return a?Ki(new RegExp(z,"i"),v.name):a}())?"tag active":"tag",x={className:H,onClick:function(){return function(){return ho.e(xp.e(v.X,
new q(null,"search-chan","search-chan",962868037)),v.name)}}(H,this,w,x,z,a,b,c,d,e,f,g,k,l,n,p)},H=ns(v.name);return React.DOM.a(x,H)}}(C,y,H,G,f,g,k,l,v,x,z),Gu.prototype.O=function(){return function(){return this.Li}}(C,y,H,G,f,g,k,l,v,x,z),Gu.prototype.P=function(){return function(a,b){return new Gu(this.ng,this.X,this.ek,this.gi,this.yh,this.ma,this.oa,this.Jk,this.mj,this.name,this.Qj,this.fi,this.gh,this.Bj,this.qa,this.pa,this.zk,this.Nh,b)}}(C,y,H,G,f,g,k,l,v,x,z));return new Gu(E,C,e,H,
l,b,z,x,v,y,d,E,L,g,G,f,a,k,null)}}();if(u(G)&&(y=v.h?v.h(C):v.call(null,C),u(y)))throw T.e(V.k("Output of %s does not match schema: %s",s([new B(null,"fnk74626","fnk74626",1227357911,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));return C}}(rq,$,g,k,l,e,f),ir($,new P(null,1,5,Q,[g],null)))}().call(null,new m(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner",
"owner",-392611939),d,new q(null,"data","data",-232669377),b],null))}a.A=2;a.o=function(a){var d=F(a);a=J(a);var e=F(a);a=I(a);return b(d,e,a)};a.k=b;return a}(),Nu=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=M.j(e,0,null);return function(){var g=new P(null,1,5,Q,[cr(new uh([Jq,$,new q(null,"owner","owner",-392611939),$,new q(null,"data","data",-232669377),new uh([Jq,$,Sq(new q(null,
"tags","tags",1771418977)),$,Sq(new q(null,"image","image",-58725096)),$,Sq(new q(null,"description","description",-1428560544)),$,new q(null,"uri","uri",-774711847),$,new q(null,"name","name",1843675177),$],!0,!1)],!0,!1),new B(null,"map74768","map74768",-1930585461,null))],null),k=Y(g),l=Y($);return jr(function(f,g,k,l,v,x,z){return function L(E){var G=f.Q();if(u(G)){var C=new P(null,1,5,Q,[E],null),y=l.h?l.h(C):l.call(null,C);if(u(y))throw T.e(V.k("Input to %s does not match schema: %s",s([new B(null,
"fnk74775","fnk74775",-218712118,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));}C=function(){for(;;){if(!me(E))throw Error(V.k("fnk called on non-map: %s",s([E],0)));var H=qr(E,new q(null,"data","data",-232669377),Xd),y=qr(H,new q(null,"name","name",1843675177),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),C=qr(H,new q(null,"uri","uri",-774711847),new P(null,
1,5,Q,[new q(null,"data","data",-232669377)],null)),R=N.j(H,new q(null,"description","description",-1428560544),null),X=N.j(H,new q(null,"image","image",-58725096),null),Z=N.j(H,new q(null,"tags","tags",1771418977),Xd),ma=qr(E,new q(null,"owner","owner",-392611939),Xd);"undefined"===typeof Hu&&(Hu=function(a,b,c,d,e,f,g,k,l,n,p,r,w,v,x,z,H,E,G,y,C,W,R){this.uri=a;this.Kk=b;this.X=c;this.fk=d;this.Oh=e;this.description=f;this.fg=g;this.ma=k;this.Cj=l;this.oa=n;this.hh=p;this.hi=r;this.name=w;this.ii=
v;this.zh=x;this.og=z;this.nj=H;this.qa=E;this.Rj=G;this.pa=y;this.$h=C;this.sh=W;this.Mi=R;this.J=0;this.C=393216},Hu.Na=!0,Hu.La="stuttaford.codex/t74800",Hu.Pa=function(){return function(a,b){return Qc(b,"stuttaford.codex/t74800")}}(ma,Z,X,R,C,y,H,G,f,g,k,l,v,x,z),Hu.prototype.wb=!0,Hu.prototype.pb=function(){return function(){return"link-item"}}(ma,Z,X,R,C,y,H,G,f,g,k,l,v,x,z),Hu.prototype.Qb=!0,Hu.prototype.Rb=function(){return function(a,b){var c=this,d=te(b)?O.e(cg,b):b,e=N.e(d,new q(null,
"search-term","search-term",356193544)),d=function(){var a={href:c.uri},b=ns(c.name);return React.DOM.a(a,b)}(),e=ns(Qp.j(Mu,function(){var a=c.fg;return Ku.h?Ku.h(a):Ku.call(null,a)}(),new m(null,2,[new q(null,"state","state",-1988618099),new m(null,1,[new q(null,"search-term","search-term",356193544),e],null),new q(null,"key","key",-1516042587),new q(null,"name","name",1843675177)],null)));return React.DOM.li({className:"link"},d,e)}}(ma,Z,X,R,C,y,H,G,f,g,k,l,v,x,z),Hu.prototype.O=function(){return function(){return this.Mi}}(ma,
Z,X,R,C,y,H,G,f,g,k,l,v,x,z),Hu.prototype.P=function(){return function(a,b){return new Hu(this.uri,this.Kk,this.X,this.fk,this.Oh,this.description,this.fg,this.ma,this.Cj,this.oa,this.hh,this.hi,this.name,this.ii,this.zh,this.og,this.nj,this.qa,this.Rj,this.pa,this.$h,this.sh,b)}}(ma,Z,X,R,C,y,H,G,f,g,k,l,v,x,z));return new Hu(C,x,ma,e,k,R,Z,b,g,z,L,E,y,H,l,E,v,G,d,f,a,X,null)}}();if(u(G)&&(y=v.h?v.h(C):v.call(null,C),u(y)))throw T.e(V.k("Output of %s does not match schema: %s",s([new B(null,"fnk74775",
"fnk74775",-218712118,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));return C}}(rq,$,g,k,l,e,f),ir($,new P(null,1,5,Q,[g],null)))}().call(null,new m(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",-392611939),d,new q(null,"data","data",-232669377),b],null))}a.A=2;a.o=function(a){var d=F(a);a=J(a);var e=F(a);a=I(a);return b(d,e,a)};a.k=b;return a}(),
Ou=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=M.j(e,0,null);return function(){var g=new P(null,1,5,Q,[cr(new uh([Jq,$,new q(null,"owner","owner",-392611939),$,new q(null,"data","data",-232669377),new uh([Jq,$,new q(null,"links","links",-654507394),$,new q(null,"name","name",1843675177),$],!0,!1)],!0,!1),new B(null,"map74959","map74959",1872337627,null))],null),k=Y(g),l=Y($);return jr(function(f,
g,k,l,v,x,z){return function L(E){var G=f.Q();if(u(G)){var C=new P(null,1,5,Q,[E],null),y=l.h?l.h(C):l.call(null,C);if(u(y))throw T.e(V.k("Input to %s does not match schema: %s",s([new B(null,"fnk74960","fnk74960",-1572739287,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));}C=function(){for(;;){if(!me(E))throw Error(V.k("fnk called on non-map: %s",s([E],0)));var H=qr(E,new q(null,
"data","data",-232669377),Xd),y=qr(H,new q(null,"name","name",1843675177),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),C=qr(H,new q(null,"links","links",-654507394),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),R=qr(E,new q(null,"owner","owner",-392611939),Xd);"undefined"===typeof Iu&&(Iu=function(a,b,c,d,e,f,g,k,l,n,p,r,w,v,x,z,H,E,y,G){this.Ph=a;this.X=b;this.links=c;this.data=d;this.Sj=e;this.pg=f;this.Dj=g;this.ma=k;this.ih=l;this.oa=n;this.name=p;this.Ah=r;
this.Cg=w;this.qa=v;this.gk=x;this.ji=z;this.oj=H;this.pa=E;this.Lk=y;this.Ni=G;this.J=0;this.C=393216},Iu.Na=!0,Iu.La="stuttaford.codex/t75005",Iu.Pa=function(){return function(a,b){return Qc(b,"stuttaford.codex/t75005")}}(R,C,y,H,G,f,g,k,l,v,x,z),Iu.prototype.wb=!0,Iu.prototype.pb=function(){return function(){return"category-item"}}(R,C,y,H,G,f,g,k,l,v,x,z),Iu.prototype.Qb=!0,Iu.prototype.Rb=function(){return function(a,b){var c=this,d=te(b)?O.e(cg,b):b,e=N.e(d,new q(null,"search-term","search-term",
356193544)),f=t(function(){var a=Lu(e,c.links);return Ku.h?Ku.h(a):Ku.call(null,a)}());if(f){var d=function(){var a=c.name;return O.j(React.DOM.h3,me(a)?ss(a):null,tg.e(Gb,me(a)?Xd:new P(null,1,5,Q,[ns(a)],null)))}(),g=function(){var a=Qp.j(Nu,f,new m(null,2,[new q(null,"state","state",-1988618099),new m(null,1,[new q(null,"search-term","search-term",356193544),e],null),new q(null,"key","key",-1516042587),new q(null,"name","name",1843675177)],null));return O.j(React.DOM.ul,me(a)?ss(a):null,tg.e(Gb,
me(a)?Xd:new P(null,1,5,Q,[ns(a)],null)))}();return React.DOM.div(null,d,g)}return null}}(R,C,y,H,G,f,g,k,l,v,x,z),Iu.prototype.O=function(){return function(){return this.Ni}}(R,C,y,H,G,f,g,k,l,v,x,z),Iu.prototype.P=function(){return function(a,b){return new Iu(this.Ph,this.X,this.links,this.data,this.Sj,this.pg,this.Dj,this.ma,this.ih,this.oa,this.name,this.Ah,this.Cg,this.qa,this.gk,this.ji,this.oj,this.pa,this.Lk,b)}}(R,C,y,H,G,f,g,k,l,v,x,z));return new Iu(k,R,C,H,d,E,g,b,L,z,y,l,a,G,e,E,v,f,
x,null)}}();if(u(G)&&(y=v.h?v.h(C):v.call(null,C),u(y)))throw T.e(V.k("Output of %s does not match schema: %s",s([new B(null,"fnk74960","fnk74960",-1572739287,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));return C}}(rq,$,g,k,l,e,f),ir($,new P(null,1,5,Q,[g],null)))}().call(null,new m(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",-392611939),d,new q(null,
"data","data",-232669377),b],null))}a.A=2;a.o=function(a){var d=F(a);a=J(a);var e=F(a);a=I(a);return b(d,e,a)};a.k=b;return a}(),Pu=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=s(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(b,d,e){var f=M.j(e,0,null);return function(){var g=new P(null,1,5,Q,[cr(new uh([Jq,$,new q(null,"owner","owner",-392611939),$,new q(null,"data","data",-232669377),new uh([Jq,$,new q(null,"categories","categories",178386610),
$],!0,!1)],!0,!1),new B(null,"map75443","map75443",-26477381,null))],null),k=Y(g),l=Y($);return jr(function(f,g,k,l,v,x,z){return function L(E){var G=f.Q();if(u(G)){var C=new P(null,1,5,Q,[E],null),y=l.h?l.h(C):l.call(null,C);if(u(y))throw T.e(V.k("Input to %s does not match schema: %s",s([new B(null,"fnk75445","fnk75445",994384777,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),k,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));
}C=function(){for(;;){if(!me(E))throw Error(V.k("fnk called on non-map: %s",s([E],0)));var H=qr(E,new q(null,"data","data",-232669377),Xd),y=qr(H,new q(null,"categories","categories",178386610),new P(null,1,5,Q,[new q(null,"data","data",-232669377)],null)),C=qr(E,new q(null,"owner","owner",-392611939),Xd);"undefined"===typeof Ju&&(Ju=function(a,b,c,d,e,f,g,k,l,n,p,r,w,v,x,z,H,E,y){this.Ae=a;this.mi=b;this.X=c;this.hk=d;this.qg=e;this.ma=f;this.jh=g;this.oa=k;this.Tj=l;this.Qh=n;this.pj=p;this.Mk=
r;this.ff=w;this.ki=v;this.qa=x;this.Ej=z;this.Bh=H;this.pa=E;this.Oi=y;this.J=0;this.C=393216},Ju.Na=!0,Ju.La="stuttaford.codex/t75531",Ju.Pa=function(){return function(a,b){return Qc(b,"stuttaford.codex/t75531")}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.wb=!0,Ju.prototype.pb=function(){return function(){return"app-view"}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.Qb=!0,Ju.prototype.Rb=function(a,b,c,d,e,f,g,k,l,n,p){return function(r,w){var v=this,x=te(w)?O.e(cg,w):w,z=N.e(x,new q(null,"search-term","search-term",
356193544)),H=N.e(x,new q(null,"search-chan","search-chan",962868037)),E=this,y=function(){var r={id:"search",type:"text",placeholder:"Search for link",autoFocus:"autofocus",value:z,onChange:function(a,b,c,d,e,f){return function(a){return ho.e(f,a.target.value)}}(null,E,w,x,z,H,a,b,c,d,e,f,g,k,l,n,p)};return ps.h?ps.h(r):ps.call(null,r)}(),G=ns(Qp.j(Ou,function(){var a=v.ff;return Ku.h?Ku.h(a):Ku.call(null,a)}(),new m(null,2,[new q(null,"state","state",-1988618099),new m(null,1,[new q(null,"search-term",
"search-term",356193544),z],null),new q(null,"key","key",-1516042587),new q(null,"name","name",1843675177)],null)));return React.DOM.div(null,y,G)}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.Xf=!0,Ju.prototype.We=function(a,b,c,d,e,f,g,k,l,n,p){return function(){var r=this,w=wp.e(r.X,new q(null,"search-chan","search-chan",962868037)),v=fo.h(1);On(function(a,b,c,d,e,f,g,k,l,n,p,w,v,x){return function(){var z=function(){return function(a){return function(){function b(c){for(;;){var d;a:{try{for(;;){var e=
a(c);if(!rf(e,new q(null,"recur","recur",-437573268))){d=e;break a}}}catch(f){if(f instanceof Object){c[5]=f;ao(c);d=new q(null,"recur","recur",-437573268);break a}throw f;}d=void 0}if(!rf(d,new q(null,"recur","recur",-437573268)))return d}}function c(){var a=[null,null,null,null,null,null,null,null,null];a[0]=d;a[1]=1;return a}var d=null,d=function(a){switch(arguments.length){case 0:return c.call(this);case 1:return b.call(this,a)}throw Error("Invalid arity: "+arguments.length);};d.F=c;d.h=b;return d}()}(function(a,
b){return function(a){var c=a[1];return 7===c?(c=a[7],c=a[2],a[7]=c,a[1]=u(c)?8:9,new q(null,"recur","recur",-437573268)):1===c?(a[2]=null,a[1]=2,new q(null,"recur","recur",-437573268)):4===c?Zn(a,7,b):6===c?(c=a[2],a[2]=c,a[1]=3,new q(null,"recur","recur",-437573268)):3===c?(c=a[2],$n(a,c)):2===c?(a[1]=4,new q(null,"recur","recur",-437573268)):9===c?(a[2]=null,a[1]=10,new q(null,"recur","recur",-437573268)):5===c?(a[2]=null,a[1]=6,new q(null,"recur","recur",-437573268)):10===c?(a[8]=a[2],a[2]=null,
a[1]=2,new q(null,"recur","recur",-437573268)):8===c?(c=a[7],c=Wp.j(r.X,new q(null,"search-term","search-term",356193544),c),a[2]=c,a[1]=10,new q(null,"recur","recur",-437573268)):null}}(a,b,c,d,e,f,g,k,l,n,p,w,v,x),a,b,c,d,e,f,g,k,l,n,p,w,v,x)}(),H=function(){var b=z.F?z.F():z.call(null);b[6]=a;return b}();return Yn(H)}}(v,w,this,a,b,c,d,e,f,g,k,l,n,p));return v}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.Kf=!0,Ju.prototype.Ve=function(){return function(){return new m(null,1,[new q(null,"search-chan",
"search-chan",962868037),fo.F()],null)}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.O=function(){return function(){return this.Oi}}(C,y,H,G,f,g,k,l,v,x,z),Ju.prototype.P=function(){return function(a,b){return new Ju(this.Ae,this.mi,this.X,this.hk,this.qg,this.ma,this.jh,this.oa,this.Tj,this.Qh,this.pj,this.Mk,this.ff,this.ki,this.qa,this.Ej,this.Bh,this.pa,b)}}(C,y,H,G,f,g,k,l,v,x,z));return new Ju(a,H,C,e,E,b,L,z,d,k,v,x,y,E,G,g,l,f,null)}}();if(u(G)&&(y=v.h?v.h(C):v.call(null,C),u(y)))throw T.e(V.k("Output of %s does not match schema: %s",
s([new B(null,"fnk75445","fnk75445",994384777,null),S.k(s([y],0))],0)),new m(null,3,[new q(null,"schema","schema",-1582001791),g,new q(null,"value","value",305978217),C,new q(null,"error","error",-978969032),y],null));return C}}(rq,$,g,k,l,e,f),ir($,new P(null,1,5,Q,[g],null)))}().call(null,new m(null,3,[new q(null,"opts","opts",155075701),f,new q(null,"owner","owner",-392611939),d,new q(null,"data","data",-232669377),b],null))}a.A=2;a.o=function(a){var d=F(a);a=J(a);var e=F(a);a=I(a);return b(d,
e,a)};a.k=b;return a}();qa("stuttaford.codex.init",function(a,b,c){return Zp.R(a,b,Pu,ze,c)});
//# sourceMappingURL=src/codex.js.map
