(ns om-tools.mixin
  "Mixins for Om made easy"
  (:require
   [om.core :as om]
                                 
                               
                  )
       
          
                                  )

     
                            
                                      
                                       
                                          
                                         
                                            
                                           
                                          
                                                   

     
   
                             
                                                                        
                                                                       
                                                                
                                                                     
                                                                    
                                            
                                   

                                       
                      
                                  
                                                     
                   
                                     
                                                        

                                               
                                       
                        
                                             
                                                                                                       
                                    
                                                 
                                          
                                       
                              
                       
                                                                
                                            

                                          
                      
                                           
                                                                                               
                                  
                                               
                                        
                                     
                            
                     
                                                              
                                                                    
                                              

                                                  
                      
                                           
                                                                                           
                                  
                                               
                            
                                     
                            
                     
                                                                    

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; defmixin validation

     
                                                      
                  
                            
                     
                            

     
                         
                                                      
             
                          
                                                             
                                                                  
                                                                                              

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Public

                  
                                

                                                 
                  
                
               
                  
                 
                
                        

                                                                                                
                                                                                             

                                                                    
                                                                                  

                                                               

           

                      
                              
                                
                                                      
                                                                        
                  
               
                                                                 
                                  
                                                
                                                     
                                                
                                                               
                          
                 
                                           
                                      

;;;;;;;;;;;; This file autogenerated from src/om_tools/mixin.cljx
